/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UsandoInterface1;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 16113009
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        bt_incluir = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        txt_nomedvd1 = new javax.swing.JTextField();
        Tittle = new javax.swing.JLabel();
        Ano = new javax.swing.JLabel();
        txt_anodvd1 = new javax.swing.JTextField();
        genero = new javax.swing.JLabel();
        txt_generodvd = new javax.swing.JTextField();
        classificacao1 = new javax.swing.JLabel();
        txt_classidvd1 = new javax.swing.JTextField();
        produtor = new javax.swing.JLabel();
        txt_produtordvd2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        pesquisabanco = new javax.swing.JButton();
        delet = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 51));

        bt_incluir.setBackground(new java.awt.Color(0, 0, 0));
        bt_incluir.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        bt_incluir.setForeground(new java.awt.Color(255, 102, 51));
        bt_incluir.setText("#INCLUIR");
        bt_incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_incluirActionPerformed(evt);
            }
        });

        titulo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        titulo.setLabelFor(titulo);
        titulo.setText("<   CADASTRO DVD   >");
        titulo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        titulo.setMaximumSize(new java.awt.Dimension(150, 20));

        txt_nomedvd1.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        txt_nomedvd1.setForeground(new java.awt.Color(255, 102, 51));
        txt_nomedvd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomedvd1ActionPerformed(evt);
            }
        });

        Tittle.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        Tittle.setForeground(new java.awt.Color(255, 102, 51));
        Tittle.setText("NOME DO FILME PARA CADASTRO:");

        Ano.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        Ano.setForeground(new java.awt.Color(255, 102, 51));
        Ano.setText("ANO DE LANÇAMENTO:");

        txt_anodvd1.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        txt_anodvd1.setForeground(new java.awt.Color(255, 102, 51));
        txt_anodvd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_anodvd1ActionPerformed(evt);
            }
        });

        genero.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        genero.setForeground(new java.awt.Color(255, 102, 51));
        genero.setText("GENÊRO:");

        txt_generodvd.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        txt_generodvd.setForeground(new java.awt.Color(255, 102, 51));
        txt_generodvd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_generodvdActionPerformed(evt);
            }
        });

        classificacao1.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        classificacao1.setForeground(new java.awt.Color(255, 102, 51));
        classificacao1.setText("CLASSIFICAÇÃO:");

        txt_classidvd1.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        txt_classidvd1.setForeground(new java.awt.Color(255, 102, 51));
        txt_classidvd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_classidvd1ActionPerformed(evt);
            }
        });

        produtor.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        produtor.setForeground(new java.awt.Color(255, 102, 51));
        produtor.setText("PRODUTOR:");

        txt_produtordvd2.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        txt_produtordvd2.setForeground(new java.awt.Color(255, 102, 51));
        txt_produtordvd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_produtordvd2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setText("</   CADASTRO DVD   >");

        pesquisabanco.setText("pesquisabanco");
        pesquisabanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisabancoActionPerformed(evt);
            }
        });

        delet.setText("delet");
        delet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(58, 58, 58)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Ano, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(delet)
                                            .addGap(52, 52, 52)
                                            .addComponent(bt_incluir, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(40, 40, 40))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(34, 34, 34)
                                    .addComponent(Tittle, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(88, 88, 88)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(produtor, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(classificacao1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_generodvd)
                            .addComponent(txt_anodvd1)
                            .addComponent(txt_nomedvd1)
                            .addComponent(txt_classidvd1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(txt_produtordvd2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(pesquisabanco))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_nomedvd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tittle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_anodvd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ano))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_generodvd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_classidvd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(produtor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_produtordvd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(classificacao1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_incluir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesquisabanco)
                    .addComponent(delet))
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("background");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_incluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_incluirActionPerformed
       
       
try
{    
String nome_dvd  =  txt_nomedvd1.getText();
Integer ano  = Integer.parseInt(txt_anodvd1.getText());
String genero_dvd = txt_generodvd.getText();
String classificacao_dvd = txt_classidvd1.getText();
String produtor_dvd= txt_produtordvd2.getText();

 JOptionPane.showMessageDialog
         (null," Titulo:" + txt_nomedvd1.getText()+"\n    "+
              " Ano:" + txt_anodvd1.getText()+"\n   "+
              " GenÃªro:" + txt_generodvd.getText()+" \n   "+
              " ClassificaÃ§Ã£o:" + txt_classidvd1.getText()+" \n   "+
              " Produtor:" + txt_produtordvd2.getText());

}
catch (Exception E)
{
           System.out.println("Minha mensagem "+E.getMessage());
           System.out.println("Minha mensagem "+E.getCause());
           System.out.println("Minha mensagem "+E.getStackTrace());
           System.out.println("Minha mensagem "+E.getClass());
}
 

       
    }//GEN-LAST:event_bt_incluirActionPerformed

    private void txt_nomedvd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomedvd1ActionPerformed
        // TODO add your handling code here:
       setTitle(null);
    }//GEN-LAST:event_txt_nomedvd1ActionPerformed

    private void txt_anodvd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_anodvd1ActionPerformed
        // TODO add your handling code here: 
        
       
       
    }//GEN-LAST:event_txt_anodvd1ActionPerformed

    private void txt_generodvdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_generodvdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_generodvdActionPerformed

    private void txt_classidvd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_classidvd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_classidvd1ActionPerformed

    private void txt_produtordvd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_produtordvd2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_produtordvd2ActionPerformed

    private void pesquisabancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisabancoActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    Connection conexao = null;
        try {
            conexao = DriverManager.getConnection("jdbc:mysql://intracker.com.br/fdb", "fdb", "fdb" );
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    try 
    {
         Statement stmt = conexao.createStatement();
    try 
    {
       // ResultSet consulta = stmt.executeQuery( "SELECT * FROM lindice_titulo" );
        String sql;
             sql = "insert into lindice_titulo(nome) values('"+txt_nomedvd1.getText()+"')";
        System.out.println(sql);
        
        stmt.execute(sql);
        
        


//            while (consulta.next()) 
//            {
//               txt_nomedvd.setText(consulta.getString("titulo"));
//               System.out.println(consulta.getString("titulo"));
//                   
//            
//            }


      
        
    }       catch (SQLException ex) { 
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            } finally 
        {
            try 
            { 
                stmt.close(); 
            } 
            catch (Throwable ignore) 
            { 

            }
        }
    } 
        catch (SQLException ex) { 
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }        finally 
        {

            try 
            { 
                conexao.close(); 
            } 
            catch (Throwable ignore) 
            { 

            }
        }
           
           
           
    
        
        
        
        
        
    }//GEN-LAST:event_pesquisabancoActionPerformed

    private void deletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletActionPerformed
       
        
         try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    Connection conexao = null;
        try {
            conexao = DriverManager.getConnection("jdbc:mysql://intracker.com.br/fdb", "fdb", "fdb" );
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    try 
    {
         Statement stmt = conexao.createStatement();
    try 
    {
       // ResultSet consulta = stmt.executeQuery( "SELECT * FROM lindice_titulo" );
        String sql;
             sql = "delete from lindice_titulo(nome) values('"+txt_nomedvd1.getText()+"')";
        System.out.println(sql);
        
        stmt.execute(sql);
        
          String del;
             del = "delete from lindice_titulo where nome='lindice'";
        System.out.println(del);
        
        stmt.execute(del);


//            while (consulta.next()) 
//            {
//               txt_nomedvd.setText(consulta.getString("titulo"));
//               System.out.println(consulta.getString("titulo"));
//                   
//            
//            }


      
        
    }       catch (SQLException ex) { 
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            } finally 
        {
            try 
            { 
                stmt.close(); 
            } 
            catch (Throwable ignore) 
            { 

            }
        }
    } 
        catch (SQLException ex) { 
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }        finally 
        {

            try 
            { 
                conexao.close(); 
            } 
            catch (Throwable ignore) 
            { 

            }
        }
           
        
        
        
        
        
        
        
    }//GEN-LAST:event_deletActionPerformed

  
  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ano;
    private javax.swing.JLabel Tittle;
    private javax.swing.JButton bt_incluir;
    private javax.swing.JLabel classificacao1;
    private javax.swing.JButton delet;
    private javax.swing.JLabel genero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JButton pesquisabanco;
    private javax.swing.JLabel produtor;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txt_anodvd1;
    private javax.swing.JTextField txt_classidvd1;
    private javax.swing.JTextField txt_generodvd;
    private javax.swing.JTextField txt_nomedvd1;
    private javax.swing.JTextField txt_produtordvd2;
    // End of variables declaration//GEN-END:variables
}
