/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjetoDvd;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author 16113009
 */
public class Cadastra_ano extends javax.swing.JFrame {

    /**
     * Creates new form Cadastra_ano
     */
    public Cadastra_ano() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bt_deletar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_ano = new javax.swing.JTextField();
        bt_incluir = new javax.swing.JButton();
        btn_atualizano = new javax.swing.JButton();
        txtAno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 51));
        jLabel1.setText("<ANO PARA CADASTRO:>");

        bt_deletar.setBackground(new java.awt.Color(0, 0, 0));
        bt_deletar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        bt_deletar.setForeground(new java.awt.Color(255, 102, 51));
        bt_deletar.setText("#DELETAR");
        bt_deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deletarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 51));
        jLabel2.setText("</ANO PARA CADASTRO:>");

        txt_ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_anoActionPerformed(evt);
            }
        });

        bt_incluir.setBackground(new java.awt.Color(0, 0, 0));
        bt_incluir.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        bt_incluir.setForeground(new java.awt.Color(255, 102, 51));
        bt_incluir.setText("#INCLUIR");
        bt_incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_incluirActionPerformed(evt);
            }
        });

        btn_atualizano.setBackground(new java.awt.Color(0, 0, 0));
        btn_atualizano.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btn_atualizano.setForeground(new java.awt.Color(255, 102, 51));
        btn_atualizano.setText("#ATUALIZAR");
        btn_atualizano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atualizanoActionPerformed(evt);
            }
        });

        txtAno.setText("jTextField1");
        txtAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_atualizano)
                            .addComponent(txt_ano, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(bt_deletar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(146, 146, 146)
                    .addComponent(bt_incluir)
                    .addContainerGap(335, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_atualizano)
                    .addComponent(bt_deletar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(154, Short.MAX_VALUE)
                    .addComponent(bt_incluir)
                    .addGap(141, 141, 141)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_deletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deletarActionPerformed
        // TODO add your handling code here:
  try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Cadastra_ano.class.getName()).log(Level.SEVERE, null, ex);
        }

    Connection conexao = null;
        try {
            conexao = DriverManager.getConnection("jdbc:mysql://intracker.com.br/fdb", "fdb", "fdb" );
        } catch (SQLException ex) {
            Logger.getLogger(Cadastra_ano.class.getName()).log(Level.SEVERE, null, ex);
        }

    try 
    {
         Statement stmt = conexao.createStatement();
    try 
    {
       // ResultSet consulta = stmt.executeQuery( "SELECT * FROM lindice_titulo" );
      
        
          String del;
             del = "delete from lindice_ano where ano='2010'";
        System.out.println(del);
        
        stmt.execute(del);

      
        
    }       catch (SQLException ex) { 
                Logger.getLogger(Cadastra_ano.class.getName()).log(Level.SEVERE, null, ex);
            } finally 
        {
            try 
            { 
                stmt.close(); 
            } 
            catch (Throwable ignore) 
            { 

            }
        }
    } 
        catch (SQLException ex) { 
            Logger.getLogger(Cadastra_ano.class.getName()).log(Level.SEVERE, null, ex);
        }        finally 
        {

            try 
            { 
                conexao.close(); 
            } 
            catch (Throwable ignore) 
            { 

            }
        }
           
        

         

    }//GEN-LAST:event_bt_deletarActionPerformed

    private void txt_anoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_anoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_anoActionPerformed

private void bt_incluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_incluirActionPerformed

     try {
            // TODO add your handling code here:

            Class.forName( "com.mysql.jdbc.Driver" );
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Cadastra_ano.class.getName()).log(Level.SEVERE, null, ex);
        }

        Connection conn = null;
        try {
            conn = DriverManager.getConnection(
                "jdbc:mysql://intracker.com.br/fdb",
                "fdb",
                "fdb" );
        } catch (SQLException ex) {
            Logger.getLogger(Cadastra_ano.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            Statement stmt = conn.createStatement();
            try {
                ResultSet rs = stmt.executeQuery( "SELECT nome FROM cliente WHERE nome = 'blue'" );
               
              
                try {
                    //        while ( rs.next() ) {
                        //               // Column numbers start at 1.
                        //               // Also there are many methods on the result set to return
                        //               //  the column as a particular type. Refer to the Sun documentation
                        //               //  for the list of valid conversions.
                        //               txt_produto.setText(rs.getString("produto"));
                        //
                        //
                        //
                        //        }
                } finally {
                    try { rs.close(); } catch (Throwable ignore) { /* Propagate the original exception
                        instead of this one that you may want just logged */ }
                }
            }           catch (SQLException ex) {
                Logger.getLogger(Cadastra_ano.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try { stmt.close(); } catch (Throwable ignore) { /* Propagate the original exception
                    instead of this one that you may want just logged */ }
            }
        }       catch (SQLException ex) {
            Logger.getLogger(Cadastra_ano.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            //It's important to close the connection when you are done with it
            try { conn.close(); } catch (Throwable ignore) { /* Propagate the original exception
                instead of this one that you may want just logged */ }
        }
    }                                              
    
    
    
    
    
    
    
    
    
}//GEN-LAST:event_bt_incluirActionPerformed

private void btn_atualizanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atualizanoActionPerformed




      
       
}//GEN-LAST:event_btn_atualizanoActionPerformed

    private void txtAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastra_ano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastra_ano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastra_ano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastra_ano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastra_ano().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_deletar;
    private javax.swing.JButton bt_incluir;
    private javax.swing.JButton btn_atualizano;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtAno;
    public javax.swing.JTextField txt_ano;
    // End of variables declaration//GEN-END:variables
}
