/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Genericas.ClasseGenericaGravar;
import javax.swing.JOptionPane;
import Classes.ClassUsuario;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 16113041
 */
public class CadUsuario extends javax.swing.JFrame {

    // DECLARACAO DE VARIAVEIS
    String c_codigo_pesquisa = "";
    int iBloqueios = 0;
    Connection CONN = null;

    /**
     * Creates new form CadUsuario
     */
    public CadUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    // DECLARACAO DE METODOS
    private void ConectaBanco() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CadCarteira.class.getName()).log(Level.SEVERE, null, ex);
        }
        CONN = null;
        try {
            CONN = DriverManager.getConnection("jdbc:mysql://intracker.com.br/fdb", "fdb", "fdb");
        } catch (SQLException ex) {
            Logger.getLogger(CadCarteira.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void bloqueios() {
        iBloqueios = 0;

        if (txtNome.getText().length() == 0) {
            iBloqueios = 1;
        };
        if (txtEndereco.getText().length() == 0) {
            iBloqueios = 2;
        };
        if (txtIdade.getText().length() == 0) {
            iBloqueios = 3;
        };
        if (txtCnpjCpf.getText().length() == 0) {
            iBloqueios = 4;
        }

        if (iBloqueios == 1) {
            JOptionPane.showMessageDialog(null, "Nome não pode ficar em branco!");
            throw new IllegalArgumentException("Nome não pode ficar em branco!");
        }
        if (iBloqueios == 2) {
            JOptionPane.showMessageDialog(null, "Endereço não pode ficar em branco!");
            throw new IllegalArgumentException("Endereço não pode ficar em branco!");
        }
        if (iBloqueios == 3) {
            JOptionPane.showMessageDialog(null, "Idade não pode ficar em branco!");
            throw new IllegalArgumentException("Idade não pode ficar em branco!");
        }
        if (iBloqueios == 4) {
            JOptionPane.showMessageDialog(null, "Cnpj/cpf não pode ficar em branco!");
            throw new IllegalArgumentException("Cnpj/cpf não pode ficar em branco!");
        }
    }

    public void limparCampos() {
        txtCelular.setText("");
        txtCnpjCpf.setText("");
        txtCodigo.setText("");
        txtEndereco.setText("");
        txtIdade.setText("");
        txtNome.setText("");
        txtTelefone.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupSexo = new javax.swing.ButtonGroup();
        btnGroupPessoa = new javax.swing.ButtonGroup();
        pnlBotoes = new javax.swing.JPanel();
        btnCadArquivo = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnCadBanco = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        pnlPrincipal = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        rbFisica = new javax.swing.JRadioButton();
        rbJuridica = new javax.swing.JRadioButton();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        txtIdade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        rbMasculino = new javax.swing.JRadioButton();
        rbFeminino = new javax.swing.JRadioButton();
        lblCnpjCpf = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtCnpjCpf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPesquisa = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Usuário");

        pnlBotoes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCadArquivo.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        btnCadArquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/document_icon.gif"))); // NOI18N
        btnCadArquivo.setText("Exportar");
        btnCadArquivo.setToolTipText("");
        btnCadArquivo.setPreferredSize(new java.awt.Dimension(85, 23));
        btnCadArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadArquivoActionPerformed(evt);
            }
        });

        btnPesquisar.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/search.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.setToolTipText("");
        btnPesquisar.setPreferredSize(new java.awt.Dimension(85, 23));
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnAlterar.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/edit_16.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setToolTipText("");
        btnAlterar.setPreferredSize(new java.awt.Dimension(85, 23));
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/delete.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setToolTipText("");
        btnExcluir.setPreferredSize(new java.awt.Dimension(85, 23));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSair.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/door_out.gif"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.setToolTipText("");
        btnSair.setPreferredSize(new java.awt.Dimension(85, 23));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnCadBanco.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        btnCadBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ic_rlt_salvar.gif"))); // NOI18N
        btnCadBanco.setText("Cadastrar");
        btnCadBanco.setToolTipText("");
        btnCadBanco.setPreferredSize(new java.awt.Dimension(85, 23));
        btnCadBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadBancoActionPerformed(evt);
            }
        });

        btnListar.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        btnListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/search.png"))); // NOI18N
        btnListar.setText("Listar");
        btnListar.setToolTipText("");
        btnListar.setPreferredSize(new java.awt.Dimension(85, 23));
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotoesLayout = new javax.swing.GroupLayout(pnlBotoes);
        pnlBotoes.setLayout(pnlBotoesLayout);
        pnlBotoesLayout.setHorizontalGroup(
            pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCadBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBotoesLayout.setVerticalGroup(
            pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBotoesLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAlterar, btnCadArquivo, btnExcluir, btnPesquisar, btnSair});

        jLabel3.setText("Telefone");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel11.setText("Pessoa");

        btnGroupPessoa.add(rbFisica);
        rbFisica.setSelected(true);
        rbFisica.setText("Fisica");
        rbFisica.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbFisicaStateChanged(evt);
            }
        });

        btnGroupPessoa.add(rbJuridica);
        rbJuridica.setText("Juridica");
        rbJuridica.setToolTipText("");
        rbJuridica.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                rbJuridicaPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbJuridica)
                    .addComponent(rbFisica))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(rbFisica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbJuridica)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtNome.setFont(new java.awt.Font("Verdana", 1, 9)); // NOI18N
        txtNome.setToolTipText("");
        txtNome.setPreferredSize(new java.awt.Dimension(150, 20));

        jLabel2.setText("Nome");

        jLabel5.setText("Endereço");

        txtCelular.setFont(new java.awt.Font("Verdana", 1, 9)); // NOI18N
        txtCelular.setToolTipText("");
        txtCelular.setPreferredSize(new java.awt.Dimension(150, 20));

        txtIdade.setFont(new java.awt.Font("Verdana", 1, 9)); // NOI18N
        txtIdade.setToolTipText("");
        txtIdade.setPreferredSize(new java.awt.Dimension(150, 20));

        jLabel1.setText("Código");

        txtTelefone.setFont(new java.awt.Font("Verdana", 1, 9)); // NOI18N
        txtTelefone.setToolTipText("");
        txtTelefone.setPreferredSize(new java.awt.Dimension(150, 20));

        jLabel7.setText("Idade");

        txtEndereco.setFont(new java.awt.Font("Verdana", 1, 9)); // NOI18N
        txtEndereco.setToolTipText("");
        txtEndereco.setPreferredSize(new java.awt.Dimension(150, 20));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setText("Sexo");

        btnGroupSexo.add(rbMasculino);
        rbMasculino.setSelected(true);
        rbMasculino.setText("Masculino");

        btnGroupSexo.add(rbFeminino);
        rbFeminino.setText("Feminino");
        rbFeminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFemininoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbMasculino)
                    .addComponent(rbFeminino))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(rbMasculino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbFeminino)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblCnpjCpf.setText("CPF");
        lblCnpjCpf.setName("lblCnpjCpf"); // NOI18N

        txtCodigo.setBackground(new java.awt.Color(204, 204, 204));
        txtCodigo.setFont(new java.awt.Font("Verdana", 1, 9)); // NOI18N
        txtCodigo.setToolTipText("");

        txtCnpjCpf.setFont(new java.awt.Font("Verdana", 1, 9)); // NOI18N
        txtCnpjCpf.setToolTipText("");
        txtCnpjCpf.setPreferredSize(new java.awt.Dimension(150, 20));

        jLabel4.setText("Celular");

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4))
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblCnpjCpf)
                                .addGap(12, 12, 12)
                                .addComponent(txtCnpjCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCnpjCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCnpjCpf))))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        tbPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbPesquisa);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:        
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnCadArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadArquivoActionPerformed
        String caminho_salvar = "";
        try {
            Classes.ClassUsuario x1 = new ClassUsuario();
            ClasseGenericaGravar g = new ClasseGenericaGravar();

            x1.setIdusuario(Integer.parseInt(txtCodigo.getText()));
            x1.setNome(txtNome.getText());
            x1.setTelefone(txtTelefone.getText());
            x1.setCelular(txtCelular.getText());
            x1.setEndereco(txtEndereco.getText());
            x1.setIdade(Integer.parseInt(txtIdade.getText()));

            if (rbFeminino.isSelected()) {
                x1.setSexo("Feminino");
            } else {
                x1.setSexo("Masculino");
            }

            if (rbFisica.isSelected()) {
                x1.setTipo_fisica_juridica("F");
            } else {
                x1.setTipo_fisica_juridica("J");
            }

            String linha_banco = "";
            linha_banco = linha_banco + " idusuario: " + x1.getIdusuario() + ';';
            linha_banco = linha_banco + " nome: " + x1.getNome() + ';';
            linha_banco = linha_banco + " celular: " + x1.getCelular() + ';';
            linha_banco = linha_banco + " endereco: " + x1.getEndereco() + ';';
            linha_banco = linha_banco + " idade: " + x1.getIdade() + ';';
            linha_banco = linha_banco + " sexo: " + x1.getSexo() + ';';
            linha_banco = linha_banco + " tipo_fisica_juridica: " + x1.getTipo_fisica_juridica() + ';';

            Genericas.CaminhoGravarLer cgl = new Genericas.CaminhoGravarLer();
            caminho_salvar = JOptionPane.showInputDialog("Digite o caminho para gravar junto com o nome", cgl.CAMINHOGRAVARLER);

            if (caminho_salvar != null) {
                g.GravarArquivo(caminho_salvar, linha_banco);
            }

        } catch (NumberFormatException E) {
            System.out.println("Telas.CadUsuario.btnCadastrarActionPerformed()" + E.getMessage() + E.getClass());
            JOptionPane.showMessageDialog(null, "Houve um erro na hora de cadastrar o usuario, verifique os campos numéricos e tente novamente!");
        } catch (Exception E) {
            System.out.println("Telas.CadUsuario.btnCadastrarActionPerformed()" + E.getMessage() + E.getClass());
            JOptionPane.showMessageDialog(null, "Houve um erro na hora de cadastrar o usuario, tente novamente!");
        } finally {
        }
    }//GEN-LAST:event_btnCadArquivoActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        ConectaBanco();
        try {
            Statement stmt = null;
            try {
                stmt = CONN.createStatement();
            } catch (SQLException ex) {
                Logger.getLogger(CadCarteira.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                // pedir o codigo para pesquisar
                c_codigo_pesquisa = JOptionPane.showInputDialog(null, "Digite o código que deseja pesquisar!");

                // comando de select
                ResultSet rs = stmt.executeQuery("SELECT * FROM mauricio_zaquia_usuario WHERE idmauricio_zaquia_usuario = " + c_codigo_pesquisa + ";");
                try {
                    while (rs.next()) {
                        if (rs != null) {
                            txtCodigo.setText(rs.getString("idmauricio_zaquia_usuario"));
                            txtNome.setText(rs.getString("nome"));
                            txtTelefone.setText(rs.getString("telefone"));
                            txtCelular.setText(rs.getString("celular"));
                            txtIdade.setText(rs.getString("idade"));
                            txtEndereco.setText(rs.getString("endereco"));
                            txtCnpjCpf.setText(rs.getString("cnpj_cpf"));

                            String sexo = rs.getString("sexo");

                            if ("M".equals(sexo)) {
                                rbMasculino.setSelected(true);
                            } else {
                                rbFeminino.setSelected(true);
                            }

                            String tfj = rs.getString("tipo_fisica_juridica");

                            if ("F".equals(tfj)) {
                                rbFisica.setSelected(true);
                            } else {
                                rbJuridica.setSelected(true);
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Registro nao encontrado!");
                        }
                    }
                } finally {
                    try {
                        rs.close();
                    } catch (Throwable ignore) {
                        /* Propagate the original exception
                         instead of this one that you may want just logged */
                    }
                    if (txtCodigo.getText().length() == 0) {
                        JOptionPane.showMessageDialog(null, "Registro nao encontrado!");
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(CadCarteira.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    stmt.close();
                } catch (Throwable ignore) {
                }
            }
        } finally {
            try {
                CONN.close();
            } catch (Throwable ignore) {
            }
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void rbFemininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFemininoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFemininoActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
    }//GEN-LAST:event_jPanel2MouseClicked

    private void rbJuridicaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_rbJuridicaPropertyChange
        // TODO add your handling code here:       
    }//GEN-LAST:event_rbJuridicaPropertyChange

    private void rbFisicaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbFisicaStateChanged
        // TODO add your handling code here:
        if (rbFisica.isSelected()) {
            lblCnpjCpf.setText("CPF");
        } else {
            lblCnpjCpf.setText("CNPJ");
        }
    }//GEN-LAST:event_rbFisicaStateChanged

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        ConectaBanco();
        try {
            Statement stmt = null;
            try {
                stmt = CONN.createStatement();
            } catch (SQLException ex) {
                Logger.getLogger(CadCarteira.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                c_codigo_pesquisa = txtCodigo.getText();

                if (c_codigo_pesquisa.length() > 0) {
                    stmt.execute("DELETE FROM mauricio_zaquia_usuario WHERE idmauricio_zaquia_usuario = " + c_codigo_pesquisa);
                    JOptionPane.showMessageDialog(null, "Excluído com sucesso!");
                    this.limparCampos();
                }
            } catch (SQLException ex) {
                Logger.getLogger(CadCarteira.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    stmt.close();
                } catch (Throwable ignore) {
                }
            }
        } finally {
            try {
                CONN.close();
            } catch (Throwable ignore) {
            }
            btnListar.doClick();
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCadBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadBancoActionPerformed

        bloqueios();

        ConectaBanco();

        try {
            Statement stmt = null;
            try {
                stmt = CONN.createStatement();
            } catch (SQLException ex) {
                Logger.getLogger(CadCarteira.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                //ResultSet rs = stmt.executeQuery( "SELECT nome FROM cliente WHERE color = 'blue'" );

                Classes.ClassUsuario x1 = new ClassUsuario();

                x1.setNome(txtNome.getText());
                x1.setTelefone(txtTelefone.getText());
                x1.setCelular(txtCelular.getText());
                x1.setEndereco(txtEndereco.getText());
                x1.setIdade(Integer.parseInt(txtIdade.getText()));
                x1.setCpf_cnpj(txtCnpjCpf.getText());

                if (rbFeminino.isSelected()) {
                    x1.setSexo("F");
                } else {
                    x1.setSexo("M");
                }

                if (rbFisica.isSelected()) {
                    x1.setTipo_fisica_juridica("F");
                } else {
                    x1.setTipo_fisica_juridica("J");
                }

                String monta_campos = "'" + x1.getNome() + "'" + ","
                        + "'" + x1.getIdade() + "'" + ","
                        + "'" + x1.getSexo() + "'" + ","
                        + "'" + x1.getEndereco() + "'" + ","
                        + "'" + x1.getTelefone() + "'" + ","
                        + "'" + x1.getCelular() + "'" + ","
                        + "'" + x1.getTipo_fisica_juridica() + "'" + ","
                        + "'" + x1.getCpf_cnpj() + "'";

                // comando de insercao
                stmt.execute("INSERT INTO mauricio_zaquia_usuario(nome,idade,sexo,endereco,telefone,celular,tipo_fisica_juridica,cnpj_cpf) VALUES (" + monta_campos + ")");

                JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");

                limparCampos();

            } catch (SQLException ex) {
                Logger.getLogger(CadCarteira.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Houve um erro na hora de inserir os dados, tente novamente!");
            } finally {
                try {
                    stmt.close();
                } catch (Throwable ignore) {
                    /* Propagate the original exception
                     instead of this one that you may want just logged */ }
            }
        } finally {
            //It's important to close the connection when you are done with it
            try {
                CONN.close();
            } catch (Throwable ignore) {
                /* Propagate the original exception
                 instead of this one that you may want just logged */ }

            btnListar.doClick();
        }
    }//GEN-LAST:event_btnCadBancoActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        limparCampos();
        String[] colunasTabela = new String[]{"Código", "Nome", "Idade", "Sexo", "Endereço", "Celular", "Telefone", "Tipo", "Cnpj_Cpf"};
        DefaultTableModel modeloTabela = new DefaultTableModel(null, colunasTabela) {
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
        tbPesquisa.setModel(modeloTabela);

        ConectaBanco();

        try {
            Statement stmt = null;
            try {
                stmt = CONN.createStatement();
            } catch (SQLException ex) {
                Logger.getLogger(CadCarteira.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                ResultSet rs = stmt.executeQuery("SELECT * FROM mauricio_zaquia_usuario");
                try {
                    while (rs.next()) {
                        if (rs != null) {
                            modeloTabela.addRow(new String[]{
                                Integer.toString(rs.getInt("idmauricio_zaquia_usuario")),
                                rs.getString("nome"),
                                rs.getString("idade"),
                                rs.getString("sexo"),
                                rs.getString("endereco"),
                                rs.getString("celular"),
                                rs.getString("telefone"),
                                rs.getString("tipo_fisica_juridica"),
                                rs.getString("cnpj_cpf")
                            }
                            );
                        } else {
                            JOptionPane.showMessageDialog(null, "Registro nao encontrado!");
                        }
                    }
                } finally {
                    try {
                        rs.close();
                    } catch (Throwable ignore) {
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(CadCarteira.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    stmt.close();
                } catch (Throwable ignore) {
                }
            }
        } finally {
            try {
                CONN.close();
            } catch (Throwable ignore) {
            }
        }
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        bloqueios();
        ConectaBanco();
        try {
            Statement stmt = null;
            try {
                stmt = CONN.createStatement();
            } catch (SQLException ex) {
                Logger.getLogger(CadCarteira.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                c_codigo_pesquisa = txtCodigo.getText();

                if (c_codigo_pesquisa.length() > 0) {

                    String l_sexo = "";
                    if (rbFeminino.isSelected()) {
                        l_sexo = "F";
                    } else {
                        l_sexo = "M";
                    };

                    String l_tipo_fisica_juridica = "";
                    if (rbFisica.isSelected()) {
                        l_tipo_fisica_juridica = "F";
                    } else {
                        l_tipo_fisica_juridica = "J";
                    };

                    stmt.execute("UPDATE mauricio_zaquia_usuario SET nome = '" + txtNome.getText() + "'"
                            + ", telefone = '" + txtTelefone.getText() + "'"
                            + ", celular = '" + txtCelular.getText() + "'"
                            + ", idade = '" + txtIdade.getText() + "'"
                            + ", endereco = '" + txtEndereco.getText() + "'"
                            + ", sexo = '" + l_sexo + "'"
                            + ", tipo_fisica_juridica = '" + l_tipo_fisica_juridica + "'"
                            + ", cnpj_cpf = '" + txtCnpjCpf.getText() + "'"
                            + "WHERE idmauricio_zaquia_usuario = " + c_codigo_pesquisa);
                    JOptionPane.showMessageDialog(null, "Alterado com sucesso!");
                    this.limparCampos();
                }
            } catch (SQLException ex) {
                Logger.getLogger(CadCarteira.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    stmt.close();
                } catch (Throwable ignore) {

                }
            }
        } finally {
            try {
                CONN.close();
            } catch (Throwable ignore) {
            }
            btnListar.doClick();
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadUsuario().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadArquivo;
    private javax.swing.JButton btnCadBanco;
    private javax.swing.JButton btnExcluir;
    private javax.swing.ButtonGroup btnGroupPessoa;
    private javax.swing.ButtonGroup btnGroupSexo;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCnpjCpf;
    private javax.swing.JPanel pnlBotoes;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JRadioButton rbFeminino;
    private javax.swing.JRadioButton rbFisica;
    private javax.swing.JRadioButton rbJuridica;
    private javax.swing.JRadioButton rbMasculino;
    private javax.swing.JTable tbPesquisa;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCnpjCpf;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
