/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Classes.ClassMovimento_carteira;
import Genericas.ClasseGenericaGravar;
import java.awt.Color;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mauricio
 */
public class OpeMovimento_carteira extends javax.swing.JFrame {

    String c_codigo_pesquisa = "";
    int iBloqueio = 0;
    Connection CONN = null;

    /**
     * Creates new form NewJFrame
     */
    public OpeMovimento_carteira() {
        initComponents();
        this.setLocationRelativeTo(null);

        //Date data = new Date(System.currentTimeMillis());
        //SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        //Date data = formato.parse("23/11/2015");
        SimpleDateFormat out = new SimpleDateFormat("dd/MM/yyyy");
        String result = out.format(System.currentTimeMillis());
        txtDataCadastro.setText(result);
    }

    // DECLARACAO DE METODOS
    private void ConectaBanco() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CadCarteira.class.getName()).log(Level.SEVERE, null, ex);
        }
        CONN = null;
        try {
            CONN = DriverManager.getConnection("jdbc:mysql://intracker.com.br/fdb", "fdb", "fdb");
        } catch (SQLException ex) {
            Logger.getLogger(CadCarteira.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void bloqueios() {
        iBloqueio = 0;

        if (txtDataCadastro.getText().length() == 0) {
            iBloqueio = 1;
        };

        if (txtValorMovimento.getText().length() == 0) {
            iBloqueio = 2;
        };

        if (txtCodigoCarteira.getText().length() == 0) {
            iBloqueio = 3;
        };

        if (iBloqueio == 1) {
            JOptionPane.showMessageDialog(null, "Data Cadastro não pode ficar em branco!");
            throw new IllegalArgumentException("Descrição não pode ficar em branco!");
        }

        if (iBloqueio == 2) {
            JOptionPane.showMessageDialog(null, "Valor Movimento não pode ficar em branco!");
            throw new IllegalArgumentException("Descrição não pode ficar em branco!");
        }

        if (iBloqueio == 3) {
            JOptionPane.showMessageDialog(null, "Codigo Carteira não pode ficar em branco!");
            throw new IllegalArgumentException("Descrição não pode ficar em branco!");
        }
    }

    public void limparCampos() {
        txtCodigoCarteira.setText("");
        txtObservacao.setText("");
        txtValorMovimento.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupCreditoDebito = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtValorMovimento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDataCadastro = new javax.swing.JTextField();
        txtCodigoCarteira = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        rbCredito = new javax.swing.JRadioButton();
        rbDebito = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        txtObservacao = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCarteiras = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        btnCadastrar = new javax.swing.JButton();
        btnCadastrar2 = new javax.swing.JButton();
        btnCadastrar1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbPesquisa2 = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtCodigoCarteiraPesquisa = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtCodigoMovimento = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        lblSaldo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Operação de Movimento");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ADICIONAR MOVIMENTAÇÃO");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("R$");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(19, 19, 19))
        );

        jLabel3.setText("Valor");

        txtValorMovimento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtValorMovimento.setToolTipText("");

        jLabel5.setText("Carteira");

        jLabel4.setText("Data Mvto.");

        txtDataCadastro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDataCadastro.setToolTipText("");

        txtCodigoCarteira.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCodigoCarteira.setToolTipText("");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/search.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        btnGroupCreditoDebito.add(rbCredito);
        rbCredito.setSelected(true);
        rbCredito.setText("Crédito");

        btnGroupCreditoDebito.add(rbDebito);
        rbDebito.setText("Débito");
        rbDebito.setToolTipText("");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(rbCredito)
                .addGap(6, 6, 6)
                .addComponent(rbDebito)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(rbCredito)
                .addComponent(rbDebito))
        );

        jLabel6.setText("Observação");

        txtObservacao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtObservacao.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDataCadastro)
                                    .addComponent(txtValorMovimento, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCodigoCarteira, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(72, 72, 72))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoCarteira, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorMovimento)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        tbCarteiras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbCarteiras);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 127, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        btnCadastrar.setFont(new java.awt.Font("Verdana", 1, 9)); // NOI18N
        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/document_icon.gif"))); // NOI18N
        btnCadastrar.setText("Exportar");
        btnCadastrar.setToolTipText("");
        btnCadastrar.setPreferredSize(new java.awt.Dimension(85, 23));
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnCadastrar2.setFont(new java.awt.Font("Verdana", 1, 9)); // NOI18N
        btnCadastrar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ic_rlt_salvar.gif"))); // NOI18N
        btnCadastrar2.setText("Salvar");
        btnCadastrar2.setToolTipText("");
        btnCadastrar2.setPreferredSize(new java.awt.Dimension(85, 23));
        btnCadastrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrar2ActionPerformed(evt);
            }
        });

        btnCadastrar1.setFont(new java.awt.Font("Verdana", 1, 9)); // NOI18N
        btnCadastrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/door_out.gif"))); // NOI18N
        btnCadastrar1.setText("Sair");
        btnCadastrar1.setToolTipText("");
        btnCadastrar1.setPreferredSize(new java.awt.Dimension(85, 23));
        btnCadastrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadastrar2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadastrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(99, 99, 99)))
        );

        jTabbedPane1.addTab("Cadastro", jPanel6);

        tbPesquisa2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tbPesquisa2);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jLabel7.setText("Carteira");

        txtCodigoCarteiraPesquisa.setBackground(new java.awt.Color(204, 204, 204));
        txtCodigoCarteiraPesquisa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCodigoCarteiraPesquisa.setToolTipText("");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/search.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnPesquisar.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/search.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar Movimentos");
        btnPesquisar.setToolTipText("");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/delete.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jLabel8.setText("Cód. Mvto");

        txtCodigoMovimento.setBackground(new java.awt.Color(204, 204, 204));
        txtCodigoMovimento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCodigoMovimento.setToolTipText("");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(txtCodigoCarteiraPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtCodigoMovimento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                .addGap(51, 51, 51))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoCarteiraPesquisa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoMovimento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        lblSaldo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSaldo.setText("Saldo: R$0");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSaldo)
                .addGap(176, 176, 176))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblSaldo)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Movimentos", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        String linha_banco = "";
        String caminho_salvar = "";
        try {
            Classes.ClassMovimento_carteira x1 = new ClassMovimento_carteira();
            ClasseGenericaGravar g = new ClasseGenericaGravar();

            x1.setIdmovimento_carteira(Integer.parseInt(txtValorMovimento.getText()));
            x1.setData_movimento(txtDataCadastro.getText());

            if (rbCredito.isSelected()) {
                x1.setValor_credito(Double.parseDouble(txtValorMovimento.getText()));
                x1.setValor_debito(0);
            } else {
                x1.setValor_credito(0);
                x1.setValor_debito(Double.parseDouble(txtValorMovimento.getText()));
            }

            //x1.setFkconta(cbConta.getSelectedIndex());
            linha_banco = linha_banco + " idmovimento_carteira " + x1.getIdmovimento_carteira() + ';';
            linha_banco = linha_banco + " data_movimento " + x1.getData_movimento() + ';';
            linha_banco = linha_banco + " codigo_conta " + x1.getFkconta() + ';';
            linha_banco = linha_banco + " valor_credito " + x1.getValor_credito() + ';';
            linha_banco = linha_banco + " valor_debito " + x1.getValor_debito() + ';';

            Genericas.CaminhoGravarLer cgl = new Genericas.CaminhoGravarLer();
            caminho_salvar = JOptionPane.showInputDialog("Digite o caminho para gravar junto com o nome", cgl.CAMINHOGRAVARLER);

            if (caminho_salvar != null) {
                g.GravarArquivo(caminho_salvar, linha_banco);
            }

        } catch (NumberFormatException E) {
            System.out.println("Telas.OpeMovimentoCarteira.btnCadastrarActionPerformed()" + E.getMessage() + E.getClass());
            JOptionPane.showMessageDialog(null, "Houve um erro na hora de cadastrar o movimento, verifique os campos numéricos e tente novamente!");
        } catch (Exception E) {
            System.out.println("Telas.OpeMovimentoCarteira.btnCadastrarActionPerformed()" + E.getMessage() + E.getClass());
            JOptionPane.showMessageDialog(null, "Houve um erro na hora de cadastrar o movimento, tente novamente!");
        } finally {
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnCadastrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrar1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCadastrar1ActionPerformed

    private void btnCadastrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrar2ActionPerformed

        bloqueios();

        ConectaBanco();
        try {
            Statement stmt = null;
            try {
                stmt = CONN.createStatement();
            } catch (SQLException ex) {
                Logger.getLogger(CadCarteira.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                // comando de insercao, verifica se credito ou debito
                if (rbCredito.isSelected()) {
                    stmt.execute("INSERT INTO mauricio_zaquia_movimento_carteira(data_movimento,observacao,valor_credito,fkcarteira) VALUES ('" + txtDataCadastro.getText()
                            + "', '" + txtObservacao.getText()
                            + "', '" + txtValorMovimento.getText()
                            + "', '" + txtCodigoCarteira.getText() + "') ");
                } else {
                    stmt.execute("INSERT INTO mauricio_zaquia_movimento_carteira(data_movimento,observacao,valor_debito,fkcarteira) VALUES ('" + txtDataCadastro.getText()
                            + "', '" + txtObservacao.getText()
                            + "', '" + txtValorMovimento.getText()
                            + "', '" + txtCodigoCarteira.getText() + "') ");
                }

                JOptionPane.showMessageDialog(null, "Movimento inserido com sucesso!");
                limparCampos();
            } catch (SQLException ex) {
                Logger.getLogger(CadCarteira.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Houve um erro na hora de inserir os dados, tente novamente!");
            } finally {
                try {
                    stmt.close();
                } catch (Throwable ignore) {
                }
            }
        } finally {

            try {
                CONN.close();
            } catch (Throwable ignore) {
            }
        }
    }//GEN-LAST:event_btnCadastrar2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String[] colunasTabela = new String[]{"Código", "Descrição", "Saldo"};
        DefaultTableModel modeloTabela = new DefaultTableModel(null, colunasTabela) {
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
        tbCarteiras.setModel(modeloTabela);

        ConectaBanco();
        try {
            Statement stmt = null;
            try {
                stmt = CONN.createStatement();
            } catch (SQLException ex) {
                Logger.getLogger(CadCarteira.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                ResultSet rs = stmt.executeQuery("SELECT sum(mzmc.valor_credito - mzmc.valor_debito) AS saldo_carteira, "
                        + "	mzc.descricao,"
                        + "	mzc.idmauricio_zaquia_carteira "
                        + "FROM mauricio_zaquia_carteira mzc "
                        + "LEFT JOIN mauricio_zaquia_movimento_carteira mzmc ON mzmc.fkcarteira = mzc.idmauricio_zaquia_carteira "
                        + "GROUP BY mzc.descricao,mzc.idmauricio_zaquia_carteira;");
                try {
                    while (rs.next()) {
                        if (rs != null) {
                            modeloTabela.addRow(new String[]{
                                Integer.toString(rs.getInt("idmauricio_zaquia_carteira")),
                                rs.getString("descricao"),
                                rs.getString("saldo_carteira")
                            }
                            );
                        } else {
                            JOptionPane.showMessageDialog(null, "Registro nao encontrado!");
                        }
                    }
                } finally {
                    try {
                        rs.close();
                    } catch (Throwable ignore) {
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(CadCarteira.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    stmt.close();
                } catch (Throwable ignore) {
                }
            }
        } finally {

            try {
                CONN.close();
            } catch (Throwable ignore) {
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked

    }//GEN-LAST:event_jPanel4MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String[] colunasTabela = new String[]{"Código", "Descrição", "Saldo"};
        DefaultTableModel modeloTabela = new DefaultTableModel(null, colunasTabela) {
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
        tbPesquisa2.setModel(modeloTabela);

        ConectaBanco();
        try {
            Statement stmt = null;
            try {
                stmt = CONN.createStatement();
            } catch (SQLException ex) {
                Logger.getLogger(CadCarteira.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                ResultSet rs = stmt.executeQuery("SELECT sum(mzmc.valor_credito - mzmc.valor_debito) AS saldo_carteira, "
                        + "	mzc.descricao,"
                        + "	mzc.idmauricio_zaquia_carteira "
                        + "FROM mauricio_zaquia_carteira mzc "
                        + "LEFT JOIN mauricio_zaquia_movimento_carteira mzmc ON mzmc.fkcarteira = mzc.idmauricio_zaquia_carteira "
                        + "GROUP BY mzc.descricao,mzc.idmauricio_zaquia_carteira;");
                try {
                    while (rs.next()) {
                        if (rs != null) {
                            modeloTabela.addRow(new String[]{
                                Integer.toString(rs.getInt("idmauricio_zaquia_carteira")),
                                rs.getString("descricao"),
                                rs.getString("saldo_carteira")
                            }
                            );
                        } else {
                            JOptionPane.showMessageDialog(null, "Registro nao encontrado!");
                        }
                    }
                } finally {
                    try {
                        rs.close();
                    } catch (Throwable ignore) {
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(CadCarteira.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    stmt.close();
                } catch (Throwable ignore) {
                }
            }
        } finally {

            try {
                CONN.close();
            } catch (Throwable ignore) {
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        String saldo_carteira = "";

        lblSaldo.setForeground(Color.BLACK);
        lblSaldo.setText("Saldo: R$0");

        c_codigo_pesquisa = txtCodigoCarteiraPesquisa.getText();

        if (c_codigo_pesquisa.length() > 0) {

            String[] colunasTabela = new String[]{"Código Movimento", "Código Carteira", "Data Movimento", "Valor Credito", "Valor Debito", "Observação"};
            DefaultTableModel modeloTabela = new DefaultTableModel(null, colunasTabela) {
                public boolean isCellEditable(int row, int col) {
                    return false;
                }
            };
            tbPesquisa2.setModel(modeloTabela);

            // PESQUISA MOVIMENTOS
            ConectaBanco();
            try {
                Statement stmt = null;
                try {
                    stmt = CONN.createStatement();
                } catch (SQLException ex) {
                    Logger.getLogger(CadCarteira.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    ResultSet rs = stmt.executeQuery("SELECT idmauricio_zaquia_movimento_carteira AS codigo_movimento,\n"
                            + "fkcarteira AS codigo_carteira,\n"
                            + "data_movimento,\n"
                            + "valor_credito,\n"
                            + "valor_debito,\n"
                            + "observacao\n"
                            + "FROM mauricio_zaquia_movimento_carteira\n"
                            + "WHERE fkcarteira = '" + txtCodigoCarteiraPesquisa.getText() + "'"
                            + "ORDER BY data_movimento, codigo_movimento");
                    try {
                        while (rs.next()) {
                            if (rs != null) {
                                modeloTabela.addRow(new String[]{
                                    Integer.toString(rs.getInt("codigo_movimento")),
                                    rs.getString("codigo_carteira"),
                                    rs.getString("data_movimento"),
                                    rs.getString("valor_credito"),
                                    rs.getString("valor_debito"),
                                    rs.getString("observacao")
                                }
                                );
                            } else {
                                JOptionPane.showMessageDialog(null, "Registro nao encontrado!");
                            }
                        }
                    } finally {
                        try {
                            rs.close();
                        } catch (Throwable ignore) {
                        }
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(CadCarteira.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    try {
                        stmt.close();
                    } catch (Throwable ignore) {
                    }
                }
            } finally {

                try {
                    CONN.close();
                } catch (Throwable ignore) {
                }
            }

            // PESQUISA SALDO
            ConectaBanco();
            try {
                Statement stmt = null;
                try {
                    stmt = CONN.createStatement();
                } catch (SQLException ex) {
                    Logger.getLogger(CadCarteira.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    ResultSet rs = stmt.executeQuery("SELECT sum(valor_credito - valor_debito) AS saldo_carteira\n"
                            + "FROM mauricio_zaquia_movimento_carteira\n"
                            + "WHERE fkcarteira = " + txtCodigoCarteiraPesquisa.getText() + " ");
                    try {
                        while (rs.next()) {
                            if (rs != null) {
                                saldo_carteira = rs.getString("saldo_carteira");
                                if (saldo_carteira != null) {
                                    if (Double.parseDouble(saldo_carteira) >= 0) {
                                        Color darkGreenColor = new Color(0, 100, 0);
                                        lblSaldo.setForeground(darkGreenColor);
                                        lblSaldo.setText("Saldo: R$" + saldo_carteira);
                                    } else {
                                        lblSaldo.setForeground(Color.RED);
                                        lblSaldo.setText("Saldo: R$" + saldo_carteira);
                                    }
                                } else {
                                    lblSaldo.setForeground(Color.BLACK);
                                    lblSaldo.setText("Saldo: R$0");
                                }

                            } else {
                                JOptionPane.showMessageDialog(null, "Registro nao encontrado!");
                            }
                        }
                    } finally {
                        try {
                            rs.close();
                        } catch (Throwable ignore) {
                        }
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(CadCarteira.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    try {
                        stmt.close();
                    } catch (Throwable ignore) {
                    }
                }
            } finally {

                try {
                    CONN.close();
                } catch (Throwable ignore) {
                }
            }
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        ConectaBanco();
        try {
            Statement stmt = null;
            try {
                stmt = CONN.createStatement();
            } catch (SQLException ex) {
                Logger.getLogger(CadCarteira.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                //c_codigo_pesquisa = JOptionPane.showInputDialog(null, "Digite o código que deseja excluir!");
                c_codigo_pesquisa = txtCodigoMovimento.getText();

                if (c_codigo_pesquisa.length() > 0) {
                    stmt.execute("DELETE FROM mauricio_zaquia_movimento_carteira WHERE idmauricio_zaquia_movimento_carteira = " + c_codigo_pesquisa);
                    JOptionPane.showMessageDialog(null, "Movimento excluído com sucesso!");
                    btnPesquisar.doClick();
                }
            } catch (SQLException ex) {
                Logger.getLogger(CadCarteira.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    stmt.close();
                } catch (Throwable ignore) {
                }
            }
        } finally {
            try {
                CONN.close();
            } catch (Throwable ignore) {
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpeMovimento_carteira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpeMovimento_carteira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpeMovimento_carteira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpeMovimento_carteira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpeMovimento_carteira().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCadastrar1;
    private javax.swing.JButton btnCadastrar2;
    private javax.swing.JButton btnExcluir;
    private javax.swing.ButtonGroup btnGroupCreditoDebito;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JRadioButton rbCredito;
    private javax.swing.JRadioButton rbDebito;
    private javax.swing.JTable tbCarteiras;
    private javax.swing.JTable tbPesquisa2;
    private javax.swing.JTextField txtCodigoCarteira;
    private javax.swing.JTextField txtCodigoCarteiraPesquisa;
    private javax.swing.JTextField txtCodigoMovimento;
    private javax.swing.JTextField txtDataCadastro;
    private javax.swing.JTextField txtObservacao;
    private javax.swing.JTextField txtValorMovimento;
    // End of variables declaration//GEN-END:variables
}
